# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'FlexiCollectionViewLayout' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FlexiCollectionViewLayout
  pod "FlexiCollectionViewLayout"

  target 'FlexiCollectionViewLayoutTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
